# Generated by Django 3.2.5 on 2021-07-09 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Title')),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Author')),
                ('pub_date', models.DateField(verbose_name='Publication Date')),
                ('isbn_num', models.CharField(max_length=100, verbose_name='ISBN')),
                ('page_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Pages')),
                ('preview_link', models.URLField(verbose_name='Preview')),
                ('language', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Language')),
            ],
        ),
    ]
