# Generated by Django 3.2.5 on 2021-07-09 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210709_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Title'),
        ),
    ]
